BOT_TOKEN="" # You know what goes here.
GUILD_ID=false # Replace false with guild ID
CHANNEL_ID=false # Replace false with channel ID.

# If you don't care about being channel specific, then just leave channel ID as false and just use the guild ID for listening to all channels in the specified guild.

